FROM elixir:1.10-alpine

RUN apk update && \
  apk add curl && \
  apk add bash && \
  apk add inotify-tools && \
  apk add --update nodejs npm nodejs-npm

RUN npm install npm@6.14.0 -g
RUN npm rebuild node-sass

RUN mix local.hex --force && \
  mix archive.install hex phx_new 1.5.1 --force && \
  mix local.rebar --force && \

RUN mkdir app